steps:
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'cd microservice_movies && pip install -r requirements.txt && python testing.py -v'
 
- name: cloud-sql-proxy
  image: gcr.io/cloudsql-docker/gce-proxy:1.17
  command:
          - "/cloud_sql_proxy"
          - "-instances=cn2021-kubernetes-colab:europe-west2:cn-database=tcp:5432"
          - "-credential_file=/secrets/service_account.json"