cd Create_and_Populate_Database

python3 AUXILIAR.py
python3 AUXILIAR2.py
python3 AUXILIAR3.py
python3 create_movies_bd.py
python3 create_streaming_bd.py
python3 populate_movies_metadata.py
python3 populate_movies_ratings.py
python3 populate_movies_streaming_plataforms.py