version: '3'
services:
  #Database MySql
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
       - db_data:/var/lib/mysql   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DatabaseGrupo4
      MYSQL_USER: root
      MYSQL_PASSWORD: goodPassword!!:)
    networks:
      - back  
networks:
  back:
volumes:
  db_data: