version: '3.7'

services:

    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=movies
        ports:
            - "5000:5432"
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql/data
volumes:
    database-data: