runtime: python
env: flex

runtime_config:
  python_version: 3


env_variables:
  CLOUD_SQL_CONNECTION_NAME: iot-teste-306319:europe-west2:database-grupo-4
  DB_USER: postgres
  DB_PASS: root
  DB_NAME: movies

  # TCP connection setup; remove if using a Unix domain socket instead
  DB_HOST: 172.17.0.1:<PORT>