openapi: "3.0.2"
info:
  title: "Movie title API"
  description: "This is a sample server that you can obtain information's about the movies title"

paths:
  /movie:
    get:
      tags:
      - "Current Movie Data"
      summary: "Call current list of movies on the streaming platform"
      description: "Access current movie data including over 450,000 movies! Current movie data is frequently updated."
      operationId: CurrentMovieData
      parameters:
        - $ref: '#/components/parameters/year'
        - $ref: '#/components/parameters/streamPlat'
        - $ref: '#/components/parameters/genres'
        
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Title'
              
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Movies not found
                type: string
                example: Not found
              
components:

  parameters:
    title:
      name: title
      in: query
      description: "**Movie title**. *Example: Toy Storie*. You can call by the movie titleans the API responds with a list of results that match a searching word."
      schema:
        type: string

    year:
      name: year
      in: query
      description: "**Realese date**. *Example: 2001*. You can call by movie year. The API responds with the list of movies realesed in that year."
      schema:
        type: string

    streamPlat:
      name: streamPlat
      in: query
      description: "**Streaming Platform**. *Example: Netflix*. We support the following platforms that you can use with the corresponded streamPlat: Netflix, Prime Video, Disney +, Hulu."
      schema:
        type: string

    genres:
      name: genres
      in: query
      description: "**Movie genre**. Search by movie genre. *Example: terror*. The API responds with the list of movies whit the same genre."
      schema:
        type: string
        
  schemas:
  
    Title:
      type: object
      properties:
        movies:
          type: array
          items:
            $ref: '#/components/schemas/GetTitle'
            
    GetTitle:
      properties:
        title:
          type: string
          description: Name of the selected Movie
          example: Toy Storie