openapi: "3.0.2"
info:
  title: "Movie rating API"
  description: "This is a sample server that you can obtain information's about the movies rating"

paths:

  /rating:
    get:
      tags:
      - "Current Movie Data"
      summary: "Call current rating for one movie"
      description: "Access current movie data including over 450,000 movies! Current movie data is frequently updated."
      operationId: CurrentMovieData2
      parameters:
        - $ref: '#/components/parameters/title'
        - $ref: '#/components/parameters/year'
        
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
              
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Rating not found
                type: string
                example: Not found

components:

  parameters:
    title:
      name: title
      in: query
      description: "**Movie title**. *Example: Toy Storie*. You can call by the movie titleans the API responds with a list of results that match a searching word."
      schema:
        type: string

    year:
      name: year
      in: query
      description: "**Realese date**. *Example: 2001*. You can call by movie year. The API responds with the list of movies realesed in that year."
      schema:
        type: string
        
    rating:
      name: rating
      in: query
      description: "**Movie rating**. The classification of the the selected movie"
      schema:
        type: string
        
  schemas:
            
    Rating:
      type: object
      properties:
        rating:
          type: integer
          items:
            $ref: '#/components/schemas/GetRating'
          
    GetRating:
      properties:
        rating:
          type: number
          description: Rating of the selected Movie
          example: 8.1