openapi: "3.0.2"
info:
  title: "Movie revenue API"
  description: "This is a sample server that you can obtain information's about the movies revenue"

tags:
- name: "Current Movie Data"
  description: "Current information about the movies"

paths:
  
  /revenue:
    get:
      tags:
      - "Current Movie Data"
      summary: "Call current revenue for one movie"
      description: "Access current movie data including over 450,000 movies! Current movie data is frequently updated."
      operationId: CurrentMovieData4
      parameters:
        - $ref: '#/components/parameters/title'
        - $ref: '#/components/parameters/year'
        
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Revenue'
              
        "404":
          description: Not found response
          content:
            text/plain:
              schema:
                title: Revenue not found
                type: string
                example: Not found

components:

  parameters:
    title:
      name: title
      in: query
      description: "**Movie title**. *Example: Toy Storie*. You can call by the movie titleans the API responds with a list of results that match a searching word."
      schema:
        type: string

    year:
      name: year
      in: query
      description: "**Realese date**. *Example: 2001*. You can call by movie year. The API responds with the list of movies realesed in that year."
      schema:
        type: string

    revenue:
      name: revenue
      in: query
      description: '**budget**. *Example: dollar*. Monye gained from making the movie.'
      schema:
        type: string
        enum: [euro, dollar]
        default: "dollar"
        
  schemas:
  
    Revenue:
      type: object
      properties:
        revenue:
          type: integer
          items:
            $ref: '#/components/schemas/GetRevenue'
            
    GetRevenue:
      properties:
        rating:
          type: number
          description: Revenue of the selected Movie
          example: 5400000