apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: movies-container
        image: eu.gcr.io/cn2021-kubernetes-colab/microservice-movies
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
          - "/cloud_sql_proxy"
          - "-instances=cn2021-kubernetes-colab:europe-west2:cn-database=tcp:5432"
          - "-credential_file=/secrets/service_account.json"
        securityContext:
          runAsNonRoot: true
        volumeMounts:
        - name: volumekey
          mountPath: /secrets/
          readOnly: true
      volumes:
      - name: volumekey
        secret:
          secretName: sa-secret