FROM python 

COPY . /microservice_movies
WORKDIR /microservice_movies

RUN pip install -r requirements.txt

#ENV APP_HOME /app
#WORKDIR $APP_HOME
#COPY . ./

ENTRYPOINT ["python"]
CMD ["server.py"]




